### ISSUE TITLE
lichking bugged

### ISSUE THREAD

**Issue by Flashaholicturbo** [Baeumchen/fixes#1]
Hi,
i test your fix for HoR. 
The First 2 Bosses works very well but i think the time between the adds are a little bit to big.
So my Issue is, after i defeat the 2 bosses i do that trash think and i speak with jaina proudmoore.
After that she destroy all the icewall but the lich king doesent move anywhere and no gunship showing up.

**Comment by Lumber-Jack-2** [comment]
any updates on this repo?
